In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
df=pd.read_csv(r"C:\Users\HP\Downloads\data\data\new1.csv")


In [29]:
X = df.drop(columns=['high_risk_applicant']).values
y = df['high_risk_applicant'].values 

In [6]:
X

array([[0, 'male', 'single', ...,
        'critical/pending loans at other banks', 13.971659240454205,
        1.791759469228055],
       [1, 'female', 'divorced/separated/married', ...,
        'existing loans paid back duly till now', 15.599069830626991,
        3.8712010109078916],
       [2, 'male', 'single', ...,
        'critical/pending loans at other banks', 14.55554132442307,
        2.4849066497880004],
       ...,
       [997, 'male', 'single', ...,
        'existing loans paid back duly till now', 13.597354548161107,
        2.4849066497880004],
       [998, 'male', 'single', ...,
        'existing loans paid back duly till now', 14.427989835456765,
        3.80666248977032],
       [999, 'male', 'single', ...,
        'critical/pending loans at other banks', 15.336335812041769,
        3.80666248977032]], dtype=object)

In [30]:
y

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [52]:
#splitting the data in 70:30 ratio for training
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)


In [53]:
X_train

array([[105, 'male', 'single', ...,
        'critical/pending loans at other banks', 16.295237147710733,
        3.1780538303479458],
       [68, 'male', 'single', ...,
        'existing loans paid back duly till now', 14.41379745750026,
        3.58351893845611],
       [479, 'male', 'single', ...,
        'critical/pending loans at other banks', 14.206200380490284,
        2.7080502011022096],
       ...,
       [629, 'male', 'single', ...,
        'existing loans paid back duly till now', 15.158897418072886,
        2.19722457733622],
       [559, 'male', 'single', ...,
        'critical/pending loans at other banks', 14.471993754152628,
        2.8903717578961645],
       [684, 'male', 'single', ...,
        'delay in paying off loans in the past', 16.103692420647572,
        3.58351893845611]], dtype=object)

In [54]:
# sorting out categorical data using label coder 
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()

In [55]:
for i in range(0,18):
    X_train[:,i]=labelencoder_X.fit_transform(X_train[:,i])

In [56]:
X_train

array([[76, 1, 3, ..., 1, 647, 16],
       [46, 1, 3, ..., 3, 240, 22],
       [346, 1, 3, ..., 1, 190, 11],
       ...,
       [447, 1, 3, ..., 3, 474, 5],
       [398, 1, 3, ..., 1, 262, 13],
       [486, 1, 3, ..., 2, 635, 22]], dtype=object)

In [57]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,

In [58]:
for i in range(0,18):
    X_test[:,i]=labelencoder_X.fit_transform(X_test[:,i])

In [59]:
X_test

array([[296, 1, 3, ..., 3, 224, 18],
       [250, 1, 3, ..., 3, 207, 3],
       [79, 1, 3, ..., 3, 158, 10],
       ...,
       [289, 1, 3, ..., 1, 125, 14],
       [138, 0, 1, ..., 4, 277, 15],
       [4, 0, 1, ..., 3, 63, 6]], dtype=object)

In [61]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier(criterion='entropy',random_state=0)
DTC.fit(X_train,y_train)
y_pred=DTC.predict(X_test)
from sklearn import metrics
print("Accuracy of DTC model: ", metrics.accuracy_score(y_pred,y_test))

Accuracy of DTC model:  0.7066666666666667


In [63]:
from sklearn.naive_bayes import GaussianNB
NBC=GaussianNB()
NBC.fit(X_train,y_train)
y_pred = NBC.predict(X_test)
print("Accuracy of NBC model: ", metrics.accuracy_score(y_pred,y_test))

Accuracy of NBC model:  0.6866666666666666


In [67]:
import graphviz.backend as be

In [68]:
from dtreeviz.trees import *


In [75]:
# fit the classifier
clf = tree.DecisionTreeClassifier(max_depth=3, random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)